name: Buid Windows and Linux Executables

on:
  push:
    branches:
      - main

jobs:
  Windows-Build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.6
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build Windows Executable
        run: pyinstaller windows.spec

      - name: Generate Pre Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.TOKEN }}
          prerelease: true
          files: |
            dist/MR.DM.exe
  
  Linux-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.6
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build Linux Executable
        run: pyinstaller linux.spec

      - name: Generate Pre Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.TOKEN }}
          prerelease: true
          files: |
            dist/MR.DM
          
